---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
#install.packages("magrittr")
#install.packages("ggplot2")
#install.packages("dplyr")
#install.packages("lubridate")
#install.packages("maps")
#install.packages("RJSONIO")
#install.packages("pROC")
library(pROC)
library(RJSONIO)
library(maps)
library(lubridate)
library(dplyr)
library(magrittr)
library(ggplot2)
library(rvest)
knitr::opts_chunk$set(echo = TRUE)
```


```{r pressure, echo=FALSE}
Stanford <- readxl::read_xlsx("Stanford_MSA_Database_for_release_06142016.xlsx")
mass_shootings_2014 <- read.csv("./Mass_shootings_2014_Locations.csv")
mass_shootings_2015 <- read.csv("./Mass_shootings_2015_Locations.csv")
mass_shootings_2016 <- read.csv("./Mass_shootings_2016_Locations.csv")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
geocodeAdddress <- function(address,which) {
  require(RJSONIO)
  url <- "http://maps.google.com/maps/api/geocode/json?address="
  url <- URLencode(paste(url, address, "&sensor=false", sep = ""))
  x <- fromJSON(url, simplify = FALSE)
  if (x$status == "OK") {
    out <- c(x$results[[1]]$geometry$location$lng,
             x$results[[1]]$geometry$location$lat)
  } else {
    out <- NA
  }
  Sys.sleep(0.2)  # API only allows 5 requests per second
  if (which==0){
    out[1]
  }else{
    out[2]
  }
}
```


```{r}
mass2014 <- mutate(mass_shootings_2014,date = mdy(Incident.Date))
mass2014 <- mutate(mass2014,week = week(date))
mass2015 <- mutate(mass_shootings_2015,date = mdy(Incident.Date))
mass2015 <- mutate(mass2015,week = week(date))
mass2016 <- mutate(mass_shootings_2016,date = mdy(Incident.Date))
mass2016 <- mutate(mass2016,week = week(date))

#used to create latitude and longitude data using town address data
#do not need to run these anymore since we have since created csv files containing this data
#mass2014 <- mutate(mass2014,location = paste(City.Or.County,","," ",State))
#mass2015 <- mutate(mass2015,location = paste(City.Or.County,","," ",State))
#mass2016 <- mutate(mass2016,location = paste(City.Or.County,","," ",State))

#mass2014loc <- mutate(mass2014,long=-10000,lat=-1000000)
#mass2015loc <- mutate(mass2015,long=-10000,lat=-1000000)
#mass2016loc <- mutate(mass2016,long=-10000,lat=-1000000)
```

```{r}
#goes through dataset and converts an address into a latitude and longitude
#do not need to run these anymore since we have since created csv files containing this data
#for(i in 1:nrow(mass2015loc)){
#  mass2015loc$long[i] <- geocodeAdddress(mass2015loc$location[i],0)
#  mass2015loc$lat[i] <- geocodeAdddress(mass2015loc$location[i],1)
#}
#for(i in 1:nrow(mass2014loc)){
#  mass2015loc$long[i] <- geocodeAdddress(mass2015loc$location[i],0)
#  mass2015loc$lat[i] <- geocodeAdddress(mass2015loc$location[i],1)
#}
#for(i in 1:nrow(mass2016loc)){
#  mass2015loc$long[i] <- geocodeAdddress(mass2015loc$location[i],0)
#  mass2015loc$lat[i] <- geocodeAdddress(mass2015loc$location[i],1)
#}
```

```{r}
#create a dataset that contains all 2014-2016 data from Gun Violence Archive datasets
massAll <- rbind(mass2014,mass2015,mass2016)
massAll <- mutate(massAll,CongressNum=ifelse(substr(date,1,4)==2013 | substr(date,1,4)==2014,113,114))

#create a dataset that contains all 2014-2016 data from the Stanford Mass Shooting Dataset
massStanford <- mutate(Stanford[3:nrow(Stanford),],Date = as.integer(Date))
massStanford <- mutate(massStanford,Date = as.Date(Date,origin="1900-01-01"))
massStanfordPresent <- filter(massStanford,as.integer(substr(massStanford$Date,1,4))>=2014)
massStanfordPresent <- mutate(massStanfordPresent,week=week(Date))
massStanfordPresent <- mutate(massStanfordPresent,CongressNum=ifelse(substr(Date,1,4)==2013 | substr(Date,1,4)==2014,113,114))
```

```{r}
#read in congressional district data for Stanford dataset locations and GVA dataset locations
#combine the two datasets into one congressional district dataset
stanfordCongressDistricts <- read.csv("Congressional Districts Stanford - Sheet1.csv")
allCongressDistricts<- read.csv("Congressional Districts - Sheet1.csv")
totalCongressDistricts <- rbind(stanfordCongressDistricts, allCongressDistricts)

#join congressional district data with Stanford mass shooting dataset
joinedStanford <- inner_join(massStanfordPresent, totalCongressDistricts, by = c("City","State"))
joinedStanfordPresent <- left_join(joinedStanford, dataCongress113, by = c("District", "State", "CongressNum"))
joinedStanfordPresentFinal <- left_join(joinedStanfordPresent, dataCongress114, by = c("District", "State", "CongressNum"))

#joining created two different variables Party.x and Party.y. We want to merge these into one variable Party
for (i in 1:140){
  if (is.na(joinedStanfordPresentFinal$Party.x[i])) {
    joinedStanfordPresentFinal$Party.x[i] <- joinedStanfordPresentFinal$Party.y[i]
  }
}

joinedStanfordPresentFinal <- joinedStanfordPresentFinal %>%
  mutate(Party = Party.x)

#join congressional district data with GVA mass shooting dataset
joinedAll <- inner_join(massAll, totalCongressDistricts, by = c("City.Or.County" = "City", "State"))
joinedAllTemp <- left_join(joinedAll, dataCongress113, by = c("District", "State", "CongressNum"))
joinedAllFinal <- left_join(joinedAllTemp, dataCongress114, by = c("District", "State", "CongressNum"))

#joining created two different variables Party.x and Party.y. We want to merge these into one variable Party
for (i in 1:893){
  if (is.na(joinedAllFinal$Party.x[i])) {
    joinedAllFinal$Party.x[i] <- joinedAllFinal$Party.y[i]
  }
}

joinedAllFinal <- joinedAllFinal %>%
  mutate(Party = Party.x)

#some issues when joining, a couple rows had Party as a numeric value
joinedAllFinalv2 <- filter(joinedAllFinal, Party == "Democrat" | Party == "Republican")

#writes these datasets to csv files
#write.csv(joinedAllFinal,"massShootings2014to2016.csv")
#write.csv(joinedStanfordPresentFinal,"stanfordShootings2014to2016.csv")
```

```{r}
#creating datasets with frequency of mass shootings per week throughout the year for our datasets
shootingFreq2014 <- mass2014 %>%
  group_by(week) %>%
  summarize(numShootings = n())

shootingFreq2015 <- mass2015 %>%
  group_by(week) %>%
  summarize(numShootings = n())

shootingFreq2016 <- mass2016 %>%
  group_by(week) %>%
  summarize(numShootings = n())

shootingFreqAll <- joinedAllFinal %>%
  group_by(week) %>%
  summarize(numShootings = n())

shootingFreqStanford <- joinedStanfordPresentFinal %>%
  group_by(week) %>%
  summarize(numShootings = n())
```

```{r}
#plot our mass shooting frequency graphs
ggplot(shootingFreq2014,aes(week,numShootings))+geom_bar(stat="identity")+ ggtitle("Shootings Throughout the Year Kaggle 2014")
ggplot(shootingFreq2015,aes(week,numShootings))+geom_bar(stat="identity")+ ggtitle("Shootings Throughout the Year Kaggle 2015")
ggplot(shootingFreq2016,aes(week,numShootings))+geom_bar(stat="identity")+ ggtitle("Shootings Throughout the Year Kaggle 2016")
ggplot(shootingFreqAll,aes(week,numShootings))+geom_bar(stat="identity")+ ggtitle("Shootings Throughout the Year Kaggle 2014-2016")
ggplot(shootingFreqStanford,aes(week,numShootings))+geom_bar(stat="identity")+ ggtitle("Shootings Throughout the Year Stanford 2014-2016")
```

```{r}
#create ggplot maps to show mass shooting locations

#get USA state map dataset, does not include Hawaii and Alaska 
map <- map_data("state")

#create USA outline with state lines
gg1 <- ggplot() + 
  geom_polygon(data = map, aes(x=long, y = lat, group = group), fill = "white", color = "black") + 
  coord_fixed(1.3)

#plot Stanford mass shooting data, color represents location political affiliation, size of a dot represents number of victims killed
gg1 + geom_point(data=joinedStanfordPresentFinal,aes(x=Longitude,y=Latitude,size=`Number of Victim Fatalities`,col=Party)) + scale_color_manual(values=c("#0004ff", "#ff0027"))

#plot GVA shooting data for 2014, 2015, and 2016. color represents week of the year, size of a dot represents number of victims killed
gg1 + geom_point(data=mass2014,aes(x=long,y=lat,size=mass2014$X..Killed,color=mass2014$week))
gg1 + geom_point(data=mass2015,aes(x=long,y=lat,size=mass2015$X..Killed,color=mass2015$week))
gg1 + geom_point(data=mass2016,aes(x=long,y=lat,size=mass2016$X..Killed,color=mass2016$week))

#plot GVA mass shooting data, color represents location political affiliation, size of a dot represents number of victims killed
joinedAllFinalv3 <- rename(joinedAllFinalv2, "Number of Victim Fatalities" = X..Killed)
gg1 + geom_point(data=joinedAllFinalv3,aes(x=long,y=lat,size=`Number of Victim Fatalities`,color=Party)) + ggtitle("Mass Shootings Kaggle 2014-2016") + scale_color_manual(values=c("#0004ff", "#ff0027"))
```

```{r}
#create dataset that includes shootings not reported by online media sources(Stanford data set)

#we want to find the proportion of shootings in Democratic and Republican districts for both datasets.
stanfordParty <- joinedStanfordPresentFinal %>% group_by(Party) %>% summarize(num=n())
allParty <- joinedAllFinal %>% group_by(Party) %>% summarize(num=n())

#shootings not reported by online media sources
missedByStanford <- anti_join(joinedAllFinal,joinedStanfordPresentFinal,by=c("City.Or.County"="City","State","week"))

#number of shootings in Democratic and Republican districts. Data from missedByStanford
missed <- missedByStanford %>% group_by(Party) %>% summarize(num=n())
```

```{r}
#Generate new column for Logistic regression on Kaggle
View(joinedAllFinal)

includedByStanford <- inner_join(joinedAllFinal,joinedStanfordPresentFinal,by=c("City.Or.County"="City","State","week"))

includedByStanford <- includedByStanford %>% mutate("IncludedStan" = 1)
includedByStanford

#Version 3 has better naming
joinedAllFinalInclusionTemp <- joinedAllFinalv3 %>% mutate("IncludedNo" = 0)
joinedAllFinalInclusionTemp

#Used to determine if it was included (Not a useful data frame)
joinedAllFinalInclusion <-  left_join(joinedAllFinalInclusionTemp,includedByStanford,by=c("City.Or.County","State","week"))
joinedAllFinalInclusion

for (i in 1:879){
  if (!is.na(joinedAllFinalInclusion$IncludedStan[i])) {
    joinedAllFinalInclusionTemp$IncludedNo[i] <- 1
  }
}

#joinedAllFinalInclusionTemp has the new column of it was included
  joinedAllFinalInclusionTemp
  

```

```{r}
#creating the log model

#first split into train and test
n <- nrow(joinedAllFinalInclusionTemp)
set.seed(100)
shooting_index <- sample(1:n, round(n*.40))
train <- joinedAllFinalInclusionTemp[shooting_index,]
test <- joinedAllFinalInclusionTemp[-shooting_index,]

#Learn Log model using train set
#First mod has 2 variables
mod <- glm( IncludedNo ~ as.factor(Party) + week , data=train)
#Second mod has 4 variables

mod2 <- glm( IncludedNo ~ as.factor(Party) + week + X..Injured + `Number of Victim Fatalities`, data=train)


#make predictions
test$p_hat <- predict(mod, test, type='response')
test$p_hat2 <- predict(mod2, test, type = 'response')

#compare

roc_obj <- roc(test$IncludedNo, test$p_hat)
roc_obj2 <- roc(test$IncludedNo, test$p_hat2)

plot(roc_obj)
plot(roc_obj2)

auc(roc_obj)
auc(roc_obj2)

```











